-- Migración: Agregar sistema de roles y permisos
-- Fecha: 2025-11-20
-- Descripción: Agrega columna de rol a users y alumnos, y tabla de permisos personalizados

-- 1. Agregar columna de rol a las tablas users y alumnos
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS rol VARCHAR(20) DEFAULT 'apoderado';

ALTER TABLE alumnos 
ADD COLUMN IF NOT EXISTS rol VARCHAR(20) DEFAULT 'apoderado';

-- 2. Crear índices para búsquedas rápidas por rol
CREATE INDEX IF NOT EXISTS idx_users_rol ON users(rol);
CREATE INDEX IF NOT EXISTS idx_alumnos_rol ON alumnos(rol);

-- 3. Crear tabla de permisos personalizados
CREATE TABLE IF NOT EXISTS permisos_usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES users(id) ON DELETE CASCADE,
  permiso VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(usuario_id, permiso)
);

-- 4. Crear índice para búsquedas rápidas de permisos
CREATE INDEX IF NOT EXISTS idx_permisos_usuario ON permisos_usuario(usuario_id);

-- 5. Actualizar el admin principal (RUT: 16484292-4)
-- Nota: El RUT se almacena sin guión ni puntos en la tabla users
UPDATE users 
SET rol = 'admin' 
WHERE rut = '164842924' OR rut = '16484292-4';

-- Verificar que el admin fue actualizado
DO $$
DECLARE
  admin_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO admin_count FROM users WHERE rol = 'admin';
  IF admin_count = 0 THEN
    RAISE NOTICE 'ADVERTENCIA: No se encontró ningún usuario con rol admin. Verifica que el RUT 16484292-4 exista en la tabla users.';
  ELSE
    RAISE NOTICE 'Se actualizó % usuario(s) con rol admin', admin_count;
  END IF;
END $$;
