-- Migración: Crear tabla items_pago con sección
-- Fecha: 2025-11-20
-- Descripción: Crea la tabla items_pago para gestionar items de cobro con opción de sección

-- Crear tabla items_pago
CREATE TABLE IF NOT EXISTS items_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_item VARCHAR(50) NOT NULL,
  descripcion TEXT NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  anio INTEGER NOT NULL,
  mes INTEGER,
  seccion VARCHAR(20), -- 'manada', 'tropa', 'compañia', 'comunidad', o NULL para todos
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Crear índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_items_pago_tipo ON items_pago(tipo_item);
CREATE INDEX IF NOT EXISTS idx_items_pago_anio ON items_pago(anio);
CREATE INDEX IF NOT EXISTS idx_items_pago_mes ON items_pago(mes);
CREATE INDEX IF NOT EXISTS idx_items_pago_seccion ON items_pago(seccion);

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para actualizar updated_at
CREATE TRIGGER update_items_pago_updated_at BEFORE UPDATE ON items_pago
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comentarios para documentación
COMMENT ON TABLE items_pago IS 'Tabla para gestionar items de cobro (cuotas, rifas, eventos, etc.)';
COMMENT ON COLUMN items_pago.tipo_item IS 'Tipo de item: cuota_mensual, rifa, evento, campamento, parche';
COMMENT ON COLUMN items_pago.descripcion IS 'Descripción del item de cobro';
COMMENT ON COLUMN items_pago.monto IS 'Monto en pesos chilenos';
COMMENT ON COLUMN items_pago.anio IS 'Año del item de cobro';
COMMENT ON COLUMN items_pago.mes IS 'Mes del item (solo para cuotas mensuales)';
COMMENT ON COLUMN items_pago.seccion IS 'Sección específica (manada/tropa/compañia/comunidad) o NULL para todos';
