-- Crear tabla logros_alumno
CREATE TABLE IF NOT EXISTS logros_alumno (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id UUID REFERENCES alumnos(id) ON DELETE CASCADE,
  titulo VARCHAR(255) NOT NULL,
  descripcion TEXT,
  fecha_obtencion DATE DEFAULT CURRENT_DATE,
  categoria VARCHAR(50) DEFAULT 'general', -- 'adelanto', 'especialidad', 'evento', 'general'
  icono VARCHAR(50), -- Emoji o nombre de icono
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Crear índice para búsquedas rápidas por alumno
CREATE INDEX IF NOT EXISTS idx_logros_alumno_id ON logros_alumno(alumno_id);

-- Insertar datos de ejemplo (Opcional, para probar)
-- Reemplazar ALUMNO_ID con un ID real si se desea probar inmediatamente
/*
INSERT INTO logros_alumno (alumno_id, titulo, descripcion, fecha_obtencion, categoria, icono)
VALUES 
  (1, 'Promesa Scout', 'Ha realizado su promesa scout ante la unidad.', '2024-04-15', 'adelanto', '⚜️'),
  (2, 'Fuego Sagrado', 'Participación destacada en el encendido del fuego.', '2024-05-20', 'evento', '🔥'),
  (1, 'Primeros Auxilios', 'Especialidad de primeros auxilios nivel 1.', '2024-06-10', 'especialidad', '⛑️');
*/
